version: "3"
services:
  backend:
    build:
      context: "./"
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - "./main:/var/www/html"
    restart: unless-stopped
    networks:
      - app
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      HOST: 0.0.0.0
    depends_on:
      - mysql
      - redis

  mysql:
    image: "mysql:8.0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    volumes:
      - "appmysql:/var/lib/mysql"
    networks:
      - app

  # Redis.
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "appredis:/data"
    restart: unless-stopped
    networks:
      - app

  ## PhpMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5005:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - app

# Network.
networks:
  app:
    driver: bridge

volumes:
  appmysql:
    driver: local
  appredis:
    driver: local
